version: '3'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://localhost:27017/booking
      - JWT_SECRET=Sudarshan@2004!!Date
    depends_on:
      - mongo
  mongo:
    image: mongo
    ports:
      - "27017:27017"
